esphome:
  name: tcl-ac
  includes:
    - tcl_climate.h

esp8266:
  board: esp07

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  password: 123

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  parity: EVEN

logger:
  level: VERBOSE
  baud_rate: 0

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new MyCustomClimate(id(uart_bus));
    App.register_component(my_custom_climate);
    return {my_custom_climate};

  climates:
    - name: "TCL a/c"